formatting

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -7,11 +7,11 @@ set -e
 
 # check for utils file
 if [ -e utils.sh ]; then
-	cd "$(dirname "${BASH_SOURCE[0]}")" \
-		&& . "utils.sh"
+    cd "$(dirname "${BASH_SOURCE[0]}")" \
+        && . "utils.sh"
 else
-	printf "\n ⚠️  ./utils.sh not found\n"
-	exit 1
+    printf "\n ⚠️  ./utils.sh not found\n"
+    exit 1
 fi
 
 printf "
@@ -38,47 +38,47 @@ chapter "Installing Dependencies"
 
 # install xcode
 if type xcode-select >&- && xpath=$( xcode-select --print-path ) &&
-	test -d "${xpath}" && test -x "${xpath}" ; then
-	print_success_muted "Xcode already installed."
+    test -d "${xpath}" && test -x "${xpath}" ; then
+    print_success_muted "Xcode already installed."
 else
-	chapter "Installing Xcode…"
-	xcode-select --install
-	print_success "Xcode installed!"
+    chapter "Installing Xcode…"
+    xcode-select --install
+    print_success "Xcode installed!"
 fi
 
 # install nvm
 if [ -x nvm ]; then
-	install "Installing NVM"
-	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
+    install "Installing NVM"
+    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
   cp swag/npm "$NVM_DIR/default-packages"
-	print_success "NVM installed!"
-	install "Installing Node LTS…"
-	nvm install --lts
-	nvm use --lts
-	nvm run node --version
-	nodev=$(node -v)
-	print_success "Using Node $nodev!"
+    print_success "NVM installed!"
+    install "Installing Node LTS…"
+    nvm install --lts
+    nvm use --lts
+    nvm run node --version
+    nodev=$(node -v)
+    print_success "Using Node $nodev!"
 else
-	print_success_muted "NVM/Node already installed. Skipping."
+    print_success_muted "NVM/Node already installed. Skipping."
 fi
 
 # install homebrew
 if ! [ -x "$(command -v brew)" ]; then
-	install "Installing Homebrew"
-	curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
-	export PATH="/usr/local/bin:$PATH"
-	print_success "Homebrew installed!"
+    install "Installing Homebrew"
+    curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
+    export PATH="/usr/local/bin:$PATH"
+    print_success "Homebrew installed!"
 else
-	print_success_muted "Homebrew already installed."
+    print_success_muted "Homebrew already installed."
 fi
 
 # install brew formulaes
 if [ -e $cwd/swag/brews ]; then
-	chapter "Installing Homebrew formulae"
+    chapter "Installing Homebrew formulae"
 
-	for brew in $(<$cwd/swag/brews); do
-		install_brews $brew
-	done
+    for brew in $(<$cwd/swag/brews); do
+        install_brews $brew
+    done
 fi
 
 chapter "Updating Homebrew formulae"
@@ -87,13 +87,13 @@ print_success "Updated"
 
 # install brew casks
 if [ -e $cwd/swag/casks ]; then
-	chapter "Installing apps via Homebrew"
+    chapter "Installing apps via Homebrew"
 
   brew tap homebrew/cask-fonts
 
-	for cask in $(<$cwd/swag/casks); do
-	    install_application_via_brew $cask
-	done
+    for cask in $(<$cwd/swag/casks); do
+        install_application_via_brew $cask
+    done
 fi
 
 # brew cleanup
@@ -104,11 +104,11 @@ print_success "Cleaned up"
 
 # install npm packages
 if [ -e $cwd/swag/npm ]; then
-	chapter "Installing npm packages"
+    chapter "Installing npm packages"
 
   for pkg in $(<$cwd/swag/npm); do
-	    install_npm_packages $pkg
-	done
+        install_npm_packages $pkg
+    done
 fi
 
 chapter "Install Pure ZSH Prompt"
